name: react-native-android-build
# name: release // TODO: Merge the ios and android release flows

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Authenticate to Github packages
        run: |
          echo "@youfoundation:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_PAT }}" >> .npmrc

      - name: Install npm dependencies
        run: npm install

      - name: Decode Homebase Keystore to file
        id: decode_keystore_file
        env:
          ENCODED_STRING: ${{ secrets.ANDROID_KEYSTORE_FILE_BASE64_ENCODED }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          KEYSTORE_FILE_PATH="${TMP_KEYSTORE_FILE_PATH}"/homebase.keystore
          echo $ENCODED_STRING | base64 -di > "${KEYSTORE_FILE_PATH}"
          echo "KEYSTORE_FILE_PATH=$KEYSTORE_FILE_PATH" >> $GITHUB_OUTPUT

      - name: Build Android Bundle
        run: cd packages/mobile/android && ./gradlew bundleRelease
        env:
          SIGNING_KEYSTORE_FILE_PATH: ${{ steps.decode_keystore_file.outputs.KEYSTORE_FILE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: homebase-feed
          path: packages/mobile/android/app/build/outputs/bundle/release/
