name: react-native-codepush-release
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Install AppCenter CLI
              run: npm install -g appcenter-cli

            - uses: actions/checkout@v3

            - name: Authenticate to Github packages
              run: |
                  echo "@youfoundation:registry=https://npm.pkg.github.com" > .npmrc
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

            - name: get-npm-version
              id: package-version
              uses: Saionaro/extract-package-version@v1.2.1
              with:
                  path: packages/mobile

            - name: Install npm dependencies
              run: npm ci

            - name: Build Android package
              run: npm run build:android-codepush -w packages/mobile

            - name: Deploy to CodePush Android
              working-directory: packages/mobile
              run: appcenter codepush release -a odinops/Homebase-Photo -d Production -c ./codepush -t ${{ steps.package-version.outputs.version }} && rm -rf codepush
              env:
                  APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN_ANDROID }}

            - name: Build iOS package
              run: npm run build:ios-codepush -w packages/mobile

            - name: Deploy to CodePush Android
              working-directory: packages/mobile
              run: appcenter codepush release -a odinops/Homebase-Photo -d Production -c ./codepush -t ${{ steps.package-version.outputs.version }} && rm -rf codepush
              env:
                  APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN_IOS }}
