name: react-native-ios-build
# name: release // TODO: Merge the ios and android release flows
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    build-ios:
        runs-on: macOS-latest

        steps:
            - uses: actions/checkout@v3

            - name: get-npm-version
              id: package-version
              uses: Saionaro/extract-package-version@v1.2.1
              with:
                  path: packages/mobile

            - name: Authenticate to Github packages
              run: |
                  echo "@youfoundation:registry=https://npm.pkg.github.com" > .npmrc
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

            - name: Install npm dependencies
              run: npm ci

            - name: Setup Ruby (bundle)
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 2.7.4
                  bundler-cache: true

            - name: Bump version
              uses: yanamura/ios-bump-version@v1
              with:
                  version: ${{ steps.package-version.outputs.version}}
                  build-number: ${{github.run_number}}
                  project-path: packages/mobile/ios

            - name: Install Pods
              run: pod install --repo-update
              working-directory: packages/mobile/ios

            - name: Build IOS App
              uses: yukiarrr/ios-build-action@v1.11.0
              with:
                  project-path: packages/mobile/ios/HomebaseFeed.xcodeproj
                  p12-base64: ${{ secrets.IOS_P12_BASE64 }}
                  mobileprovision-base64: ${{ secrets.PHOTOS_IOS_MOBILE_PROVISION_BASE64 }}
                  code-signing-identity: 'iPhone Distribution'
                  team-id: ${{ secrets.IOS_TEAM_ID }}
                  certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
                  workspace-path: packages/mobile/ios/HomebaseFeed.xcworkspace
                  scheme: HomebaseFeed

            - uses: actions/upload-artifact@v3
              with:
                  name: photo-native-app
                  #path: packages/mobile/android/app/build/outputs/bundle/release/
                  path: output.ipa

            # - name: 'Upload app to TestFlight'
            #   working-directory: packages/mobile/ios
            #   uses: apple-actions/upload-testflight-build@v1
            #   with:
            #     app-path: 'output.ipa'
            #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
            #     api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
            #     api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
