name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: get-npm-version
        id: package-version
        uses: Saionaro/extract-package-version@v1.2.1
        with:
          path: packages/mobile

      - name: Authenticate to Github packages
        run: |
          echo "@homebase-id:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: |
          pytest
